version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: bitcoin-fix-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=bitcoin_fix_dev

  # MongoDB UI (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: bitcoin-fix-mongo-express-dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:alpine
    container_name: bitcoin-fix-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  # FIX simulator for development testing
  fixsimulator:
    image: quickfixj/quickfixj-server:latest
    container_name: bitcoin-fix-simulator-dev
    ports:
      - "9878:9878"
    volumes:
      - ./config/quickfixj.cfg:/etc/quickfixj/quickfixj.cfg
    restart: unless-stopped
